{
    "request_number": 10,
    "timestamp": "2025-10-12 21:06:37",
    "model": "x-ai/grok-4-fast",
    "prompt_variant": "zero-shot-clusters",
    "total_tokens": 7665,
    "avg_prob": 0.8981433590135591,
    "perplexity": 1.1134079988057932,
    "struct_metrics": {
        "avg_cyclomatic_complexity": -1.0,
        "ast_depth": -1,
        "avg_function_size_lines": -1.0,
        "import_redundancy_ratio": -1.0
    },
    "semantic_metrics": {
        "syntax_valid": false,
        "flake8_error_count": -1,
        "mypy_error_count": -1
    },
    "execution_metrics": {
        "execution_success": false,
        "execution_time_sec": 0.708,
        "exception_type": "RuntimeError",
        "exception_message": "File \"/app/main.py\", line 606\n    def ensure_daily_financial_data(self):\n    ^\nIndentationError: expected an indented block after function definition on line 603",
        "runtime_output": "File \"/app/main.py\", line 606\n    def ensure_daily_financial_data(self):\n    ^\nIndentationError: expected an indented block after function definition on line 603"
    },
    "total_credibility": 0.0
}